#include<iostream>
/* 1. C++ 11: Compiler generated function */
/*
* C++ 03:
* 1. Default Constructor (generated only if no constructor is declared by the user)
* 2. Copy Constructor (C++ 11: generated only if no 3, 4, 5, 6 is declared by the user)
* 3. Copy Assignment Operator (C++ 11:generated only if no 2, 4, 5, 6 is declared by the user)
* 4. Destructor 
*
* C++ 11:
* 5. Move Constructor (C++ 11: generated only if no 2, 3, 4, 6 is declared by the user)
* 6. Move Assignment Operator (C++ 11: generated only if no 2, 3, 4, 5 is declared by the user)
 */
class dog {}; //1, 2, 3, 4, 5, 6 will be generated by the compiler
//is euqivalent to:
class dog{
    //C++ 03:
    dog();
    dog(const dog& d);
    dog& operator=(const dog& d);
    ~dog();
    //c++ 11:
    dog(const dog&& d);
    dog& operator=(dog&& d);
};

class cat{ //3, 4 will be generated by compiler. (3 is deprecated)
    cat(const cat& c); //copy constructor. 
};

class Duck{ // 4 will be generated by compiler
    Duck(Duck&& d); //Move constructor
};

class Frog{ // 4 ...
    Frog(Frog&& f, int x = 0);//Move constructor
    Frog(int x = 0); //Default constructor
    Frog(Frog& f, int x = 0) //Copy Constructor
};

class Fish{ // 1, 2, 3 ... (2, 3 are deprecated)
    ~Fish(); //Destructor
};

class Cow{ // 1, 2, 4 ... (2 is deprecated. Still there, should not use it according to the above rule. Explicit define 2 if we want to use it.)
    Cow& operator=(const Cow& C) = delete; // Still count as copy assignment operator declared by the user
};














